development:
  adapter: postgresql
  encoding: unicode
  database: contactbook3
  pool: 5
  host: localhost
  username: postgres
  password: developer


  #host: localhost
  #port: 5432


  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:

  #min_messages: warning


test: &test
  adapter: postgresql
  encoding: unicode
  database: contactbook3_test
  pool: 5
  host: localhost
  username: postgres
  password: developer


cucumber:
  <<: *test
